name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
